version: '3'

networks:
  app-tier:
    driver: bridge


services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=zaim_test
      - POSTGRES_USER=your_name
      - POSTGRES_PASSWORD=your_password
    networks:
      - app-tier

  app:
    build: ./
    command: bash -c "uvicorn app.server:app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - app-tier